# Generated by Django 2.2 on 2019-04-09 17:20

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_header', models.CharField(max_length=255)),
                ('ingredients_header', models.CharField(default='Składniki:', max_length=50)),
                ('description', models.TextField()),
                ('difficulty_level', models.CharField(choices=[('EASY', 'łatwe'), ('MEDIUM', 'średnie'), ('HARD', 'trudne')], default='EASY', max_length=10)),
                ('status', model_utils.fields.StatusField(choices=[('DRAFT', 'draft'), ('PUB', 'published')], default='DRAFT', max_length=100, no_check_for_status=True)),
                ('published_at', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', when={'published'})),
                ('tags', models.ManyToManyField(to='blog.Tag')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
