# Generated by Django 2.2 on 2019-04-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190429_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='ingredients',
            name='amount',
            field=models.ManyToManyField(to='blog.Amount'),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='unit',
            field=models.ManyToManyField(to='blog.Unit'),
        ),
    ]
